# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 924bb0a37dfca5ea0c87da4b275eae54f0c23179b65c15699ae9eb49e38b6f779995dea3e069bbdc9f5d94eb3ab2ccfc6a03fdf0b9b47932d3d7ee8f6e67f6d5

test:
  secret_key_base: bfb24a2787dac93fa6c09f69fc6fb44814f8054eab7469034ba34f69a42b153c88068f80e606a53de6ca4da63d6ff4e7421d7eca550360a0cb337c5c4fe8ca5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
